# Generated by Django 5.1.15 on 2026-09-30 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Permission and module codes must be uppercase letters, digits, and underscores only.', regex='^[A-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Permission and module codes must be uppercase letters, digits, and underscores only.', regex='^[A-Z0-9_]+$')]),
        ),
    ]
